# Configuration
configuration:
  - any: ['github/**/*', './*']

doc: ./**/README.md

# Push Notification
pushNotification: messages/**/*

# Frontend
frontend: frontend/**/*

assets: frontend/src/assets/*

environment: frontend/src/environments/*

dependencies: frontend/package.json
