[build]
  publish = "dist/frontend"
  functions = "dist/functions"

[dev]
  framework = "#custom"
  command = "npm run start"
  autoLaunch = true
  targetPort = 4200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"