[build]
  base = "frontend/"
  publish = "dist/frontend"
  command = "ng build --prod"
  functions = "functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
