name: Dev Preview
on:
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    if: github.event.label.name == 'preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@main
        with:
          ref: "${GITHUB_REF##*/}"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Build
        run: |
          npm install
          npm run build
        working-directory: ./frontend
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: "./frontend/dist/frontend"
          netlify-config-path: "netlify.toml"
          production-deploy: true
          deploy-message: "GITHUB ACTIONS"
          enable-commit-status: true
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
