name: Deploy Website
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          enable-commit-status: true
          netlify-config-path: "netlify.toml"
          deploy-message: "GITHUB ACTIONS"
          publish-dir: "./frontend/dist/frontend"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
