name: Deploy Website
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Netlify Actions
      uses: nwtgck/actions-netlify@v1.1.11
      with:
        enable-commit-status: true
        netlify-config-path: "netlify.toml"
        deploy-message: "GITHUB ACTIONS"
