name: Dev Preview
on:
  workflow_run:
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    if: github.event.label.name == 'preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@main
        with:
          ref: "${GITHUB_REF##*/}"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Build
        run: |
          npm install
          npm run build
      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: "RVmC8bJSBbGlAMJI6asFr5Uw"
